### ISSUE TITLE
Conda Installation

### ISSUE THREAD

**Issue by msouff** [erdc-cm/RAPIDpy#29]
I cannot install RAPIDpy using conda. Here is what I'm getting:

![screen shot 2017-08-10 at 12 10 49 pm](https://user-images.githubusercontent.com/17328135/29184998-307ff01a-7dc5-11e7-8933-471ba538e038.png)

I'm using a 32bit machine and makes me wonder if RAPIDpy is only available in conda for 64bit.

**Comment by snowman2** [comment]
It is only available for 64 bit: https://anaconda.org/conda-forge/rapidpy

**Comment by msouff** [comment]
I installed it manually for 32 bit, but I think this is still an issue. The fix would be to either make it available for 32bits or to specify in the documentation that the conda installation is only for 64bit.

**Comment by snowman2** [comment]
@msouff, would you mind doing a PR addressing the documentation for this issue?

**Comment by msouff** [comment]
Yes. I can do that sometime next week.
